apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      name: portal
      labels:
        app: portal
    spec:
      containers:
        - name: portal-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 5m
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          envFrom:
            - configMapRef:
                name: portal-config-map
